name: Claude Code

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  claude-code:
    # Only run when @claude is mentioned
    if: |
      (github.event.issue.body && contains(github.event.issue.body, '@claude')) ||
      (github.event.comment.body && contains(github.event.comment.body, '@claude'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Claude Code
        run: |
          npm install -g @anthropic-ai/claude-code

      - name: Run Claude Code
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract the task from issue body or comment
          if [ "${{ github.event_name }}" = "issue_comment" ]; then
            TASK="${{ github.event.comment.body }}"
          else
            TASK="${{ github.event.issue.body }}"
          fi

          # Remove @claude mention and run the task
          TASK=$(echo "$TASK" | sed 's/@claude//g')

          echo "Running Claude Code with task: $TASK"
          claude-code --non-interactive "$TASK"

      - name: Create Pull Request
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git
          git config user.name "Claude Code Bot"
          git config user.email "claude-code@anthropic.com"

          # Check if there are changes
          if [[ -n $(git status -s) ]]; then
            BRANCH_NAME="claude-code/issue-${{ github.event.issue.number }}-$(date +%s)"
            git checkout -b "$BRANCH_NAME"
            git add .
            git commit -m "Address issue #${{ github.event.issue.number }}

            🤖 Generated with Claude Code

            Co-Authored-By: Claude <noreply@anthropic.com>"
            git push origin "$BRANCH_NAME"

            gh pr create \
              --title "Fix: Issue #${{ github.event.issue.number }}" \
              --body "Addresses #${{ github.event.issue.number }}

              🤖 Generated with [Claude Code](https://claude.com/claude-code)" \
              --base master \
              --head "$BRANCH_NAME"
          fi

      - name: Comment on Issue
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            MESSAGE="✅ I've completed the task and created a pull request with the changes."
          else
            MESSAGE="❌ I encountered an issue while working on this task. Please check the workflow logs for details."
          fi

          gh issue comment ${{ github.event.issue.number }} --body "$MESSAGE"
